# Generated by Django 4.2.2 on 2023-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_from_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
