# Generated by Django 4.2.2 on 2023-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_from_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactions_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
