# Generated by Django 4.2.2 on 2023-07-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_transactions_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account_number',
        ),
    ]
