# Generated by Django 4.2.2 on 2023-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_transaction_from_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
