# Generated by Django 4.2.2 on 2023-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
