# Generated by Django 4.2.2 on 2023-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transaction_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
