# Generated by Django 4.2.2 on 2023-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactions_type',
            field=models.CharField(choices=[('Credited', 'Credited'), ('Debited', 'Debited')], max_length=20),
        ),
    ]
